os: osx
osx_image: xcode11.3
language: node_js
node_js: 12
# credit: https://github.com/develar/onshape-desktop-shell/blob/master/.travis.yml
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+/"
cache:
  directories:
    - node_modules
    - $HOME/.cache/yarn
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
script:
  - yarn test
  - yarn compile
  # read: https://www.electron.build/configuration/publish#githuboptions
  - yarn build --macos --linux --windows --publish never
