# This workflow will do a clean install of node dependencies,
# build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Building on all platforms using latest node versions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Note: The Ubuntu 20.04 virtual environment is currently provided as
        # a preview only. The ubuntu-latest YAML workflow label still uses the
        # Ubuntu 18.04 virtual environment.
        # see: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#github-hosted-runners
        os: [macos-latest, windows-latest, ubuntu-20.04]
        node: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: yarn --frozen-lockfile
      - run: yarn test
      - run: yarn compile

      - if: startsWith( matrix.node, '12' )
        run: yarn build --publish never

      - if: startsWith( matrix.node, '14' )
        # https://www.electron.build/configuration/publish#githuboptions
        run: yarn build --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
